### ISSUE TITLE
:RubyBrowseGem refactor

### ISSUE THREAD

**Issue by vinibispo** [vinibispo/ruby.nvim#11]
Code of RubyBrowseGem function is kinda weird
@cuducos

**Comment by cuducos** [comment]
Do you know if treesiter has a grammar for Gemfile?

**Comment by vinibispo** [comment]
> Do you know if treesiter has a grammar for Gemfile?

I don't have idea

**Comment by cuducos** [comment]
Just checked, it does… 
Probably using tree-sitter grammar we can get the _method_ nodes with `gem` and select their first argument : )

**Comment by vinibispo** [comment]
> Just checked, it does… Probably using tree-sitter grammar we can get the _method_ nodes with `gem` and select their first argument : )

Perfect
